# Generated by Django 6.0.2 on 2026-02-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Category',
            new_name='category',
        ),
    ]
