# Generated by Django 6.0.2 on 2026-02-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0002_rename_category_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
